apiVersion: devops.kubesphere.io/v1alpha1
kind: S2iBuilder
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: s2ibuilder-triger
  namespace: default
spec:
  # Add fields here
  config:
    displayName: "For Test"
    sourceUrl: "https://github.com/kubesphere/s2i-python-container"
    imageName: kubespheredev/s2i-test-python
    tag: latest
    builderPullPolicy: if-not-present
    export: true
    contextDir: "examples/setup-test-app/"
    pushAuthentication:
      username: UserShouldEnterUserName
      password: UserShouldEnterUserPassword
    builderImage: kubespheredev/python-35-centos7
