apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    app: s2i-metrics
    control-plane: s2i-controller-manager
    controller-tools.k8s.io: "1.0"
  name: s2ioperator-metrics-service
  namespace: kubesphere-devops-system
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: s2i-trigger-service
    control-plane: s2i-controller-manager
    controller-tools.k8s.io: "1.0"
  name: s2ioperator-trigger-service
  namespace: kubesphere-devops-system
spec:
  selector:
    control-plane: s2i-controller-manager
    controller-tools.k8s.io: '1.0'
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: s2ioperator
  namespace: kubesphere-devops-system
  labels:
    control-plane: s2ioperator
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: s2i-controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: s2ioperator
  template:
    metadata:
      labels:
        control-plane: s2i-controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
        - command:
            - /manager
          image: kubespheredev/s2ioperator:latest
          imagePullPolicy: Always
          name: manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: S2IIMAGENAME
              value: kubespheredev/s2irun:latest
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 20Mi
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: s2i-webhook-server-cert
---
apiVersion: v1
kind: Secret
metadata:
  name: s2i-webhook-server-cert
  namespace: kubesphere-devops-system
type: Opaque
data:
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBeHFOK1NaaktCeU9iSGpPeExldG9PSFIwbFJlNmdIZUN0eXVRNUIxOWhRRkcyRUMvClJodGlIMW9lem5lVkRDZmlVMVY2a3FBb3djUFZmdWg0U1BSWVhVc2d6U3N4bFBqWlBBbUxPbDFmODlMNEFaSHEKckw1VDdxNzNZdEJuTHVMOWpZRkE5bmpwcitkWW16cTF2YVordGdsQzkvY3EwRUlHVEIwWlZnanJHaEROeEVZRApPT0liczgydDdrdlhsdy9ycDNubGovV2VGRFFIU3UvY0I3QzA1a3ZjeFYyUlRWK0pGNkZRbWptZ0hZendzQ2JKCm9GbDdvM1d1Z2lvMXJIWmdXak1pNkxIVzNNVGpXWmNpSUxBb0VYZTJUU2dlOWhOUzcyalhPVldPNlcxb1RFTzgKTkhzWUQ0MndBU0xmcXRQd3Vjandla1VYczM0ck5uV0pieTBkT3dJREFRQUJBb0lCQUQ1MktyLzV5NDF6Sk5QYQpiVnlES2NLVzNCSUY1QitCZFJra0dldWhXbGI0ajg1d2piVDk1MXowZWJ0eTN1dHpuemVWS1hYeDV0OEhOWnN5CmZxQnlOVmNneUsrN1pWdnk1Rng4bzhzMmtYV2FZV0lkQUM1UnF4TGk4ZWVnb05HZGp4MXdCMzE1aUFKSVBSU1MKNFpOQlI1YjJVcGltb0UvY2N4NThCL3VGMG1mZlVpcko5OFBZMmRiWHloNlB3azhSOGxTV1FtMUFVY1VqQWpzbgp6a3BMcUVVNk5heUZTcW90ZXRhNDRTNEV6bm80c21JOHREUkpaOGhmQzNqb21uMWFIN0ZKODN1U1NsY3JnLzBMCnM2L0VKSmtka1ZWWXZGWXJ1L0VVSTNvMHlCYk1mc1V6anFGMSszMW5rVjRPTnduc01Jd3pSV3JyMlN4Mnk5UHoKMFZXMWJBRUNnWUVBKzMxYjAvZE1PVXpvWUlIdS9NcVBwTklnOUxjZzYrM0RGZHBtTmFUVUJaRnhaREpxVGhmMwpDbmRsTHFGTU94eEYrN0VHSjFJR2lxNjh6bFlYSWw0WUZyV3RZTUUvZWhIdy9CNHZsTWYzNHRUTkJuRThCa2M1CmRiN3B4MXRFMjJNZHNjVm1sT1ZWVVR1N3l3STE5eExtWVJ3cFJtL3BkQ0o0RXJxQTBhekEwZThDZ1lFQXlqTjgKQ29OZDNRb09QQTF1dTJqZTNqU2srbGdBYjB5OStEaGRBc2hOdndXM2pZOEpvZ1hOekh5Y2JwdHYwcnM1cnJNRAp1Kzd6TUZadEdlbHdwZXBWK2Y5dkNtN3RoTkxuY1JCSEpVRDRhajF2VTh4TFI4MWNCaXhTU081MXBFWjBCRGhUClhlZThlUkl4SFYrRzRlN3htdGMzUzlvTFNqaVR0UGpIdTUzRWhYVUNnWUJEMEdIYW5teW5adDJpYUdjUk0yM1kKZS9EM0RBcU1rK2h2RkIxTGljN0NVWjNKN3U1TGNKcms3NTBSSGQxNGN2OU1CMGdwZ2l6UmFKenc1cllHUm1rbwpkb1R4K2lvcnVIckxBVGpEWGNpeUdiL1BaT2xTcUJJT2RoU0Q5VkJ6K0I0aHVhRVh0VjkwTUM5TFpxVTJvcG9NCnhaTTdzeUc0ZHpMNW1lRHlxU3ExY1FLQmdCNUxabXRBMFdCYnNGUkpBdTByUWpEeW5FRXh6Q2JnelptU0FFVjUKYzBTS2U3ekcwSCtvOVBPTk8vYktiUSthbzRMTUtXUVA0Zm05Q1MyWHJ4djhweE1FdFVOUDZXQThKUmJvaEhCTgpjcXFnTjd6TFlBQUxBWjJmS0ZqcStVODZpd2xTMHhLL3RKcERJbjZ2SUV0YmZIRmhpMVJlLzlBSCtBRm1RSzZZCmJhZzlBb0dBVS9CZGtpS2cxb2ZKQXljcmdkTHNxRGxNQy9sSURPU3JvbjRVOUZoN25hS2pVUStoQ0tKa1lTdnMKWE9IdlRQdGUyN1NPdngxcWo3N1RMbE5YY1pDbitxVkhnS3NaNmEyQk5uSmtidkRodVRxallFYXVLSFc5aHM3dQpLUDUydDlXenA3NTF6MFVzaW91b0tnb2NHaU4wRVBENk1ETE9CRTF0ZlBaZDRmWnF4WUk9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhFQ0NRRHBnZUc4ak9PQldqQU5CZ2txaGtpRzl3MEJBUXNGQURCSU1Rc3dDUVlEVlFRR0V3SkQKVGpFTE1Ba0dBMVVFQ0F3Q1NFSXhDekFKQmdOVkJBb01BbEZETVI4d0hRWURWUVFEREJaM1pXSm9iMjlyTFhObApjblpsY2kxelpYSjJhV05sTUI0WERUSXdNVEV6TURBME1UQXdObG9YRFRRNE1EUXhOekEwTVRBd05sb3daVEVMCk1Ba0dBMVVFQmhNQ1EwNHhDekFKQmdOVkJBZ01Ba2hDTVFzd0NRWURWUVFLREFKUlF6RThNRG9HQTFVRUF3d3oKZDJWaWFHOXZheTF6WlhKMlpYSXRjMlZ5ZG1salpTNXJkV0psYzNCb1pYSmxMV1JsZG05d2N5MXplWE4wWlcwdQpjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4cU4rU1pqS0J5T2JIak94CkxldG9PSFIwbFJlNmdIZUN0eXVRNUIxOWhRRkcyRUMvUmh0aUgxb2V6bmVWRENmaVUxVjZrcUFvd2NQVmZ1aDQKU1BSWVhVc2d6U3N4bFBqWlBBbUxPbDFmODlMNEFaSHFyTDVUN3E3M1l0Qm5MdUw5allGQTluanByK2RZbXpxMQp2YVordGdsQzkvY3EwRUlHVEIwWlZnanJHaEROeEVZRE9PSWJzODJ0N2t2WGx3L3JwM25sai9XZUZEUUhTdS9jCkI3QzA1a3ZjeFYyUlRWK0pGNkZRbWptZ0hZendzQ2JKb0ZsN28zV3VnaW8xckhaZ1dqTWk2TEhXM01UaldaY2kKSUxBb0VYZTJUU2dlOWhOUzcyalhPVldPNlcxb1RFTzhOSHNZRDQyd0FTTGZxdFB3dWNqd2VrVVhzMzRyTm5XSgpieTBkT3dJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFVWit5NVdZTGw1WFdoL3hEQXNmTFp4RWI3Ck55RlpqZUJ5cUN4Tk9uZlQ5Q3VGbUdrRzVENE1lMnNKdVlqeW5samZoRWlQQlE1YllUUjhDYWJnKzlKNGRrQXgKbWQ3VFY2S0Z5eDBid0VIc015dVI3TlpKbnNQcXFKSUp3QUFOUjZCeCtCOE9ka2xzOFdJYWRvODVuc0h5ckJVZQpvYlNZZnZpK3lTUlZoVHdyeHRLWHc4L0FTclBrMkdId0F2a2gwOTUxRUdCSG5tb3hIcFVobjNEdnhLTGNQbzFJClB6UkJiQkFwK3dkaEVEQzFuR3RTZyt3bUJleWNtaHpMTkVRaU1FNzQxajNPN0NkdHQ0UWU3UjFKOTlieUdCazkKYThSZ2ZWKzREOGxjald0TDJrQlJ3OEZZWm1qMkMxRU5aM25jWWYzalpDODJZL2hYTXlLMDVlRFh1bEVICi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZekNDQWt1Z0F3SUJBZ0lKQU13cmJrdlBGeVorTUEwR0NTcUdTSWIzRFFFQkN3VUFNRWd4Q3pBSkJnTlYKQkFZVEFrTk9NUXN3Q1FZRFZRUUlEQUpJUWpFTE1Ba0dBMVVFQ2d3Q1VVTXhIekFkQmdOVkJBTU1GbmRsWW1odgpiMnN0YzJWeWRtVnlMWE5sY25acFkyVXdIaGNOTWpBeE1UTXdNRFF4TURBMldoY05ORGd3TkRFM01EUXhNREEyCldqQklNUXN3Q1FZRFZRUUdFd0pEVGpFTE1Ba0dBMVVFQ0F3Q1NFSXhDekFKQmdOVkJBb01BbEZETVI4d0hRWUQKVlFRRERCWjNaV0pvYjI5ckxYTmxjblpsY2kxelpYSjJhV05sTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBdVAzTEN3TFo4K1g5K1FxMFB2U2xJeitZTWFLWHNHSlIxSVM5TWVGZ2w3akp5V0t1CldqeWhkLzd5Ty9SZVNRQSswVHppcmUxR3kzWmYyekxOT1JPNkRqZ0I1cVl2ZDY2YzlheDU0TmtEYnhRVkM3YjIKSXJacC9TWEJ1cjZsUCtMY0VJN2x6UHNidDNWMnNob05CNUlGbnYzaDV6QXNadGJ4MURvQ2Y3Rzg1VDFiOVFlOQpFRDFFT2JRaHZWYk00YTVQa1ZmMWJJK3d1S25QdzlxTEVFRVZrNFg1KzkzbHlZbWhFRldMN0l1RnhnaE1McnQzCjYzSWRPc3R0VjA2ZE44ZEtNaWw0Z0RMang3NUgxVldnZTBGT004TnFkYzl5OGtQaFhVY3plbGFTaUgrUkNKRSsKVW56eW1GbXZva3FpQ1A5Y0V1VnpjYmhNdStRRmFITG1PRFVaV3dJREFRQUJvMUF3VGpBZEJnTlZIUTRFRmdRVQovYnRCWll6eTZlQ0tUdHZqRnluRDFxLzJYemN3SHdZRFZSMGpCQmd3Rm9BVS9idEJaWXp5NmVDS1R0dmpGeW5ECjFxLzJYemN3REFZRFZSMFRCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFaVnNzUk4zVk03MFEKREY1UFA5Sk5JTG5iMVVoQjVCVTZrcGRsZ0FBNHNlR05zc3UrLzYxV1k5Y2FJdVlnQkl4UWRtT1dLMUptTVhUMgowbFRESzJWUy8wVE9RSW4xUmJaWXo1dmpVWms1ZUhBY0hrQUFPQUVFRVFBUVJCUFl6ZmJBTnpmL2RtTTBhVFczCkZSK1YwOGhoUDRjNzVRSEhJdi9iZENWeGUrRHJHOFM0d2p2OUIrbDAvakw3SG84ajRnUTJ5OHhkMyt0OE9VK0cKaVlmNkNMUUNQT3dLMVVUeUU1RkF0aHppays0ZWdSSUFERWZpUlRtQmhXblBMQnpaYlZGOXBBRjVPbnF4eGNvSAp6NlJKdXRLckpRZEdCY2NldFF4V2NzKzJZcGlhcjQ4WHMxbVhGdWhlcHdLNUJMWlhWMGxnYXJJUmxZeFJiWDVGCmJwamM5eWkxVmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==