apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: kubesphere-devops-system
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    control-plane: s2i-controller-manager
