apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: s2i-selfsigned-issuer
  namespace: kubesphere-devops-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: s2i-webhook-serving-cert  # this name should match the one appeared in kustomizeconfig.yaml
  namespace: kubesphere-devops-system
spec:
  # $(SERVICE_NAME) and $(SERVICE_NAMESPACE) will be substituted by kustomize
  commonName: $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  dnsNames:
    - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: s2i-selfsigned-issuer
  secretName: s2i-webhook-server-cert # this secret will not be prefixed, since it's not managed by kustomize
